### ISSUE TITLE
Release new version of this extension

### ISSUE THREAD

**Issue by bricesanchez** [refinery/refinerycms-acts-as-indexed#10]
Hello @parndt ! 

Could you release a new version please ?

Thank you :)

**Comment by bricesanchez** [comment]
🆙  😄

**Comment by bricesanchez** [comment]
Release if and after merging #12 please.

**Comment by parndt** [comment]
https://rubygems.org/gems/refinerycms-acts-as-indexed/versions/3.0.0

**Comment by bricesanchez** [comment]
Nice! Thanks!
